# Generated by Django 3.2.5 on 2023-10-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_nmae',
            new_name='last_name',
        ),
    ]
